struct Win32 {
	typedef MAYBE_AS(FLOAT, float) Float;
	typedef MAYBE_AS(CHAR, char) Char;
	typedef MAYBE_AS(BYTE, unsigned char) Byte;
	typedef MAYBE_AS(SHORT, short) Short;
	typedef MAYBE_AS(USHORT, unsigned short) UShort;
	typedef MAYBE_AS(WORD, unsigned short) Word;
	typedef MAYBE_AS(INT, int) Int;
	typedef MAYBE_AS(UINT, unsigned int) UInt;
	typedef MAYBE_AS(UINT32, unsigned int) UInt32;
	typedef MAYBE_AS(LONG, long) Long;
	typedef MAYBE_AS(ATOM, Word) Atom;
	typedef MAYBE_AS(SIZE_T, unsigned long long) SizeT;
	typedef MAYBE_AS(DWORD, unsigned long) DWord;
	typedef MAYBE_AS(LONG_PTR, long long) LongPtr;
	typedef MAYBE_AS(ULONG_PTR, unsigned long long) ULongPtr;
	typedef MAYBE_AS(UINT_PTR, unsigned long long) UIntPtr;
	typedef MAYBE_AS(LONGLONG, long long) LongLong;
	typedef MAYBE_AS(COLORREF, DWord) ColorRef;
	typedef MAYBE_AS(LARGE_INTEGER, LongLong) LargeInteger;
	typedef MAYBE_AS(HANDLE, void*) Handle;
	typedef MAYBE_AS(CHAR*, Char*) StrPtr;
	typedef MAYBE_AS(CONST CHAR*, const Char*) ConstStrPtr;
	struct WndHandle_Internal {
		int i;
	};
	struct IconHandle_Internal {
		int i;
	};
	struct InstanceHandle_Internal {
		int i;
	};
	typedef WndHandle_Internal* WndHandle;
	typedef IconHandle_Internal* IconHandle;
	typedef IconHandle_Internal* CursorHandle;
	typedef InstanceHandle_Internal* InstanceHandle;
	typedef MAYBE_AS(LRESULT, LongPtr) LResult;
	typedef MAYBE_AS(HRESULT, Long) HResult;
	typedef MAYBE_AS(LPARAM, LongPtr) LParam;
	typedef MAYBE_AS(WPARAM, UIntPtr) WParam;

	constexpr static int max_path = 260;
	constexpr static UInt wm_user = 0x0400;

	struct KeyCode {
		constexpr static UShort LButton = 0x01;
		constexpr static UShort RButton = 0x02;
		constexpr static UShort Cancel = 0x03;
		constexpr static UShort MButton = 0x04;
		constexpr static UShort XButton1 = 0x05;
		constexpr static UShort XButton2 = 0x06;
		constexpr static UShort Back = 0x08;
		constexpr static UShort Tab = 0x09;
		constexpr static UShort Clear = 0x0C;
		constexpr static UShort Return = 0x0D;
		constexpr static UShort Shift = 0x10;
		constexpr static UShort Control = 0x11;
		constexpr static UShort Menu = 0x12;
		constexpr static UShort Pause = 0x13;
		constexpr static UShort Capital = 0x14;
		constexpr static UShort Kana = 0x15;
		constexpr static UShort Hangul = 0x15;
		constexpr static UShort ImeOn = 0x16;
		constexpr static UShort Junja = 0x17;
		constexpr static UShort Final = 0x18;
		constexpr static UShort HanjaKanji = 0x19;
		constexpr static UShort ImeOff = 0x1A;
		constexpr static UShort Escape = 0x1B;
		constexpr static UShort Convert = 0x1C;
		constexpr static UShort NonConvert = 0x1D;
		constexpr static UShort Accept = 0x1E;
		constexpr static UShort ModeChange = 0x1F;
		constexpr static UShort Space = 0x20;
		constexpr static UShort Prior = 0x21;
		constexpr static UShort Next = 0x22;
		constexpr static UShort End = 0x23;
		constexpr static UShort Home = 0x24;
		constexpr static UShort Left = 0x25;
		constexpr static UShort Up = 0x26;
		constexpr static UShort Right = 0x27;
		constexpr static UShort Down = 0x28;
		constexpr static UShort Select = 0x29;
		constexpr static UShort Print = 0x2A;
		constexpr static UShort Execute = 0x2B;
		constexpr static UShort Snapshot = 0x2C;
		constexpr static UShort Insert = 0x2D;
		constexpr static UShort Delete = 0x2E;
		constexpr static UShort Help = 0x2F;
		constexpr static UShort Number0 = 0x30;
		constexpr static UShort Number1 = 0x31;
		constexpr static UShort Number2 = 0x32;
		constexpr static UShort Number3 = 0x33;
		constexpr static UShort Number4 = 0x34;
		constexpr static UShort Number5 = 0x35;
		constexpr static UShort Number6 = 0x36;
		constexpr static UShort Number7 = 0x37;
		constexpr static UShort Number8 = 0x38;
		constexpr static UShort Number9 = 0x39;
		constexpr static UShort LWin = 0x5B;
		constexpr static UShort RWin = 0x5C;
		constexpr static UShort Apps = 0x5D;
		constexpr static UShort Sleep = 0x5F;
		constexpr static UShort Numpad0 = 0x60;
		constexpr static UShort Numpad1 = 0x61;
		constexpr static UShort Numpad2 = 0x62;
		constexpr static UShort Numpad3 = 0x63;
		constexpr static UShort Numpad4 = 0x64;
		constexpr static UShort Numpad5 = 0x65;
		constexpr static UShort Numpad6 = 0x66;
		constexpr static UShort Numpad7 = 0x67;
		constexpr static UShort Numpad8 = 0x68;
		constexpr static UShort Numpad9 = 0x69;
		constexpr static UShort Multiply = 0x6A;
		constexpr static UShort Add = 0x6B;
		constexpr static UShort Separator = 0x6C;
		constexpr static UShort Subtract = 0x6D;
		constexpr static UShort Decimal = 0x6E;
		constexpr static UShort Divide = 0x6F;
		constexpr static UShort F1 = 0x70;
		constexpr static UShort F2 = 0x71;
		constexpr static UShort F3 = 0x72;
		constexpr static UShort F4 = 0x73;
		constexpr static UShort F5 = 0x74;
		constexpr static UShort F6 = 0x75;
		constexpr static UShort F7 = 0x76;
		constexpr static UShort F8 = 0x77;
		constexpr static UShort F9 = 0x78;
		constexpr static UShort F10 = 0x79;
		constexpr static UShort F11 = 0x7A;
		constexpr static UShort F12 = 0x7B;
		constexpr static UShort F13 = 0x7C;
		constexpr static UShort F14 = 0x7D;
		constexpr static UShort F15 = 0x7E;
		constexpr static UShort F16 = 0x7F;
		constexpr static UShort F17 = 0x80;
		constexpr static UShort F18 = 0x81;
		constexpr static UShort F19 = 0x82;
		constexpr static UShort F20 = 0x83;
		constexpr static UShort F21 = 0x84;
		constexpr static UShort F22 = 0x85;
		constexpr static UShort F23 = 0x86;
		constexpr static UShort F24 = 0x87;
		constexpr static UShort NavigationView = 0x88;
		constexpr static UShort NavigationMenu = 0x89;
		constexpr static UShort NavigationUp = 0x8A;
		constexpr static UShort NavigationDown = 0x8B;
		constexpr static UShort NavigationLeft = 0x8C;
		constexpr static UShort NavigationRight = 0x8D;
		constexpr static UShort NavigationAccept = 0x8E;
		constexpr static UShort NavigationCancel = 0x8F;
		constexpr static UShort NumLock = 0x90;
		constexpr static UShort Scroll = 0x91;
		constexpr static UShort LShift = 0xA0;
		constexpr static UShort RShift = 0xA1;
		constexpr static UShort LControl = 0xA2;
		constexpr static UShort RControl = 0xA3;
		constexpr static UShort LMenu = 0xA4;
		constexpr static UShort RMenu = 0xA5;
		constexpr static UShort BrowserBack = 0xA6;
		constexpr static UShort BrowserForward = 0xA7;
		constexpr static UShort BrowserRefresh = 0xA8;
		constexpr static UShort BrowserStop = 0xA9;
		constexpr static UShort BrowserSearch = 0xAA;
		constexpr static UShort BrowserFavorites = 0xAB;
		constexpr static UShort BrowserHome = 0xAC;
		constexpr static UShort VolumeMute = 0xAD;
		constexpr static UShort VolumeDown = 0xAE;
		constexpr static UShort VolumeUp = 0xAF;
		constexpr static UShort MediaNextTrack = 0xB0;
		constexpr static UShort MediaPrevTrack = 0xB1;
		constexpr static UShort MediaStop = 0xB2;
		constexpr static UShort MediaPlayPause = 0xB3;
		constexpr static UShort LaunchMail = 0xB4;
		constexpr static UShort LaunchMediaSelect = 0xB5;
		constexpr static UShort LaunchApp1 = 0xB6;
		constexpr static UShort LaunchApp2 = 0xB7;
		constexpr static UShort OEM_1 = 0xBA;
		constexpr static UShort OEM_Plus = 0xBB;
		constexpr static UShort OEM_Comma = 0xBC;
		constexpr static UShort OEM_Minus = 0xBD;
		constexpr static UShort OEM_Period = 0xBE;
		constexpr static UShort OEM_2 = 0xBF;
		constexpr static UShort OEM_3 = 0xC0;
		constexpr static UShort GamepadA = 0xC3;
		constexpr static UShort GamepadB = 0xC4;
		constexpr static UShort GamepadX = 0xC5;
		constexpr static UShort GamepadY = 0xC6;
		constexpr static UShort GamepadRightShoulder = 0xC7;
		constexpr static UShort GamepadLeftShoulder = 0xC8;
		constexpr static UShort GamepadLeftTrigger = 0xC9;
		constexpr static UShort GamepadRightTrigger = 0xCA;
		constexpr static UShort GamepadDpadUp = 0xCB;
		constexpr static UShort GamepadDpadDown = 0xCC;
		constexpr static UShort GamepadDpadLeft = 0xCD;
		constexpr static UShort GamepadDpadRight = 0xCE;
		constexpr static UShort GamepadMenu = 0xCF;
		constexpr static UShort GamepadView = 0xD0;
		constexpr static UShort GamepadLeftThumbstickButton = 0xD1;
		constexpr static UShort GamepadRightThumbstickButton = 0xD2;
		constexpr static UShort GamepadLeftThumbstickUp = 0xD3;
		constexpr static UShort GamepadLeftThumbstickDown = 0xD4;
		constexpr static UShort GamepadLeftThumbstickRight = 0xD5;
		constexpr static UShort GamepadLeftThumbstickLeft = 0xD6;
		constexpr static UShort GamepadRightThumbstickUp = 0xD7;
		constexpr static UShort GamepadRightThumbstickDown = 0xD8;
		constexpr static UShort GamepadRightThumbstickRight = 0xD9;
		constexpr static UShort GamepadRightThumbstickLeft = 0xDA;
		constexpr static UShort OEM_4 = 0xDB;
		constexpr static UShort OEM_5 = 0xDC;
		constexpr static UShort OEM_6 = 0xDD;
		constexpr static UShort OEM_7 = 0xDE;
		constexpr static UShort OEM_8 = 0xDF;
		constexpr static UShort OEM_AX = 0xE1;
		constexpr static UShort OEM_102 = 0xE2;
		constexpr static UShort ICO_Help = 0xE3;
		constexpr static UShort ICO_00 = 0xE4;
		constexpr static UShort ProcessKey = 0xE5;
		constexpr static UShort ICO_Clear = 0xE6;
		constexpr static UShort Packet = 0xE7;
		constexpr static UShort Attn = 0xF6;
		constexpr static UShort CrSel = 0xF7;
		constexpr static UShort ExSel = 0xF8;
		constexpr static UShort ErEOF = 0xF9;
		constexpr static UShort Play = 0xFA;
		constexpr static UShort Zoom = 0xFB;
		constexpr static UShort Noname = 0xFC;
		constexpr static UShort PA1 = 0xFD;
		constexpr static UShort OEM_Clear = 0xFE;
	};

#if USE_REAL_TYPES
	typedef FILETIME FileTime;
	typedef WIN32_FIND_DATAA FindDataA;
	typedef POINT Point;
	typedef POINTS Points;
	typedef RECT Rect;
	typedef WINDOWPLACEMENT WindowPlacement;
	typedef CRITICAL_SECTION CriticalSection;
	typedef WAVEFORMATEX WaveFormatEx;
#else
	struct FileTime {
		DWord dwLowDateTime;
		DWord dwHighDateTime;
	};

	struct FindDataA {
		DWord dwFileAttributes;
		FileTime ftCreationTime;
		FileTime ftLastAccessTime;
		FileTime ftLastWriteTime;
		DWord nFileSizeHigh;
		DWord nFileSizeLow;
		DWord dwReserved0;
		DWord dwReserved1;
		Char cFileName[max_path];
		Char cAlternateFileName[14];
	};

	struct Point {
		Long x;
		Long y;
	};

	struct Points {
		Short x;
		Short y;
	};

	struct Rect {
		Long left;
		Long top;
		Long right;
		Long bottom;
	};

	struct WindowPlacement {
		UInt length;
		UInt flags;
		UInt showCmd;
		Point ptMinPosition;
		Point ptMaxPosition;
		Rect rcNormalPosition;
		Rect rcDevice;
	};

#pragma pack(push, 8)
	struct CriticalSection {
		MAYBE_AS(PRTL_CRITICAL_SECTION_DEBUG, void*) DebugInfo;
		MAYBE_AS(LONG, Long) LockCount;
		MAYBE_AS(LONG, Long) RecursionCount;
		MAYBE_AS(HANDLE, Handle) OwningThread;
		MAYBE_AS(HANDLE, Handle) LockSemaphore;
		MAYBE_AS(ULONG_PTR, ULongPtr) SpinCount;
	};
#pragma pack(pop)

	struct WaveFormatEx {
		Word wFormatTag;
		Word nChannels;
		DWord nSamplesPerSec;
		DWord nAvgBytesPerSec;
		Word nBlockAlign;
		Word wBitsPerSample;
		Word cbSize;
	};
#endif

	static Handle CreateThreadSimple(void* lpStartAddress, void* lpParameter);
};